##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: sfserver
  user: vagrant
  sudo: yes

#  vars_files:
#    - settings.yml

  roles:
    - common
    - mongodb
    - web
