---

- name: PHP5 | Install required packages.
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5
    - php-pear
    - php5-ldap
    - php5-curl
    - php5-intl
    - php5-cli
    - php5-xdebug
    - php5-dev
    - php5-mysql
    - php5-json
  tags: php5
  notify: Restart apache

- name: PHP5 | PHPDev | Update pear channels
  command: pear update-channels

- name: PHP5 | PHPDev | Update pear packages
  command: pear upgrade-all

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: PHP5 | Install PHP 5 Mongo Module
  command: pecl install mongo
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr"
  tags: php5

- name: Mongodb | Configure PHP to use PECL MongoDB extension
  template: src=etc-php5-conf-d-mongo-ini.j2 dest=/etc/php5/mods-available/mongo.ini

- name: Mongodb | Enable extension mongo.ini
  command: php5enmod ALL mongo state=present

- name: PHP5 | Configuration /etc/php5/apache2/php.ini
  template: src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  notify: Restart apache

- name: PHP5 | Configuration /etc/php5/cli/php.ini
  template: src=etc-php5-cli-php-ini.j2 dest=/etc/php5/cli/php.ini
  notify: Restart apache
