---

- name: Composer | Install composer.phar
  command: php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"

- name: Composer | rename composer.phar to composer
  command: mv composer.phar /usr/local/bin/composer