---

- name: Apache2 | Install required packages
  apt: pkg=apache2
  tags: apache2

- name: Apache2 | Active module rewrite
  command: a2enmod rewrite
  tags: apache2
  notify: Restart apache

- name: Apache2 | Add vhost for project sf2
  template: src=vhost-sf2.conf.j2 dest=/etc/apache2/sites-available/{{ web.domain }}.conf
  tags: apache2

- name: Apache2 | Activate vhost
  command: a2ensite {{ web.domain }}.conf
  tags: apache2
  notify: Restart apache