---

# Install custom vim
- name: VIM | Clone vim config
  sudo: false
  git: repo=https://github.com/lesmyrmidons/vim-config.git
       dest=/home/{{ user }}/.vim-config
       update=yes
       accept_hostkey=yes

- name: VIM | Created symlink (vimrc)
  sudo: false
  file: src=/home/{{ user }}/.vim-config/vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }} state=link

- name: VIM | Created symlink (.vim/)
  sudo: false
  file: src=/home/{{ user }}/.vim-config/vim dest=/home/{{ user }}/.vim owner={{ user }} group={{ user }} state=link

- name: Font | Create folder .font if not exist
  sudo: false
  command: mkdir ~/.font
  ignore_errors: yes

- name: Font | Add font for vim
  unarchive: src=../files/powerline.tar.gz dest=/home/{{ user }}/.font
