---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: Restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade debian
  apt: upgrade=dist

- name: Install lists packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - vim
    - zsh
    - curl
    - wget
    - python-software-properties                 # for example use "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"
    - aptitude
    - bash-completion
    - openssh-server
    - git
    - git-core
    - git-flow
    - git-email
    - git-extras
    - htop
    - ack-grep
    - ccze
    - tmux
    - tig
    - unzip
    - tar
    - gzip
    - bzip2